sudo: required
dist: trusty
language: node_js
node_js: 
  - "node"

env:
  - NODE_ENV=test

addons:
  apt:
    sources:
      - google-chrome
      - travis-ci/sqlite3
    packages:
      - google-chrome-stable
      - google-chrome-beta
      - sqlite3

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - yarn global add @angular/cli
  - yarn global add karma
  - cd server
  - yarn
  - yarn build
  - cd ../pacha-client
  - yarn
  - ng build

script: 
  - cd ../pacha-client && yarn test
  - cd ../server && yarn test
